public class BillCalculator implements Billable {

    private Customer person;
    // 10% tax
    private static final double TAX_PERCENT = 0.10;

    public BillCalculator(Customer person) {
        this.person = person;
    }

    // slab rate logic
    public double calcCharge() {
        double totalUnits = person.getTotalUnits();

        if (totalUnits <= 100) {
            return totalUnits * 1.00;

        } 
        else if (totalUnits <= 300) {
            return (100 * 1.00) + ((totalUnits - 100) * 2.00);

        } 
        else {
            return (100 * 1.00) + (200 * 2.00) + ((totalUnits - 300) * 5.00);

        }
    }

    // tax amount calculation
    public double calcTax() {
        return calcCharge() * TAX_PERCENT;
    }

    @Override
    public double calculateTotal() {
        return calcCharge() + calcTax();
    }

    public void printBill() {
        System.out.println("\n--- SmartPay Bill Receipt ---");
        System.out.println("Name        : " + person.getPersonName());
        System.out.println("Old Reading : " + person.getMeterBefore() + " units");
        System.out.println("New Reading : " + person.getMeterNow() + " units");
        System.out.println("Units Used  : " + person.getTotalUnits() + " units");
        System.out.println("-----------------------------");
        System.out.println("Base Amount : $" + calcCharge());
        System.out.println("Tax (10%)   : $" + calcTax());
        System.out.println("Total Bill  : $" + calculateTotal());
        System.out.println("-----------------------------");
        System.out.println("Bill generated by SmartPay.");
        System.out.println();
    }
}
